set(_CATKIN_CURRENT_PACKAGE "abb")
set(abb_VERSION "0.0.0")
set(abb_MAINTAINER "labbare <labbare@todo.todo>")
set(abb_PACKAGE_FORMAT "2")
set(abb_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(abb_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(abb_BUILDTOOL_DEPENDS "catkin")
set(abb_BUILDTOOL_EXPORT_DEPENDS )
set(abb_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(abb_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(abb_TEST_DEPENDS )
set(abb_DOC_DEPENDS )
set(abb_URL_WEBSITE "")
set(abb_URL_BUGTRACKER "")
set(abb_URL_REPOSITORY "")
set(abb_DEPRECATED "")